apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "demo-micronaut-java"
spec:
  template:
    spec:
      containers:
        - image: "gcr.io/demo-micronaut-java/jib-image"
          name: "demo-micronaut-java"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
